ln -sf /home/cupcake/code/dotfiles/zshrc ~/.zshrc
ln -sf /home/cupcake/code/dotfiles/xinitrc ~/.xinitrc
ln -sf /home/cupcake/code/dotfiles/Xresources ~/.Xresources
ln -sf /home/cupcake/code/dotfiles/nvidia-settings-rc ~/.nvidia-settings-rc
ln -sf /home/cupcake/code/dotfiles/oh-my-zsh ~/.oh-my-zsh
ln -sf /home/cupcake/code/dotfiles/i3 ~/.i3
ln -sf /home/cupcake/code/dotfiles/config/aliases ~/.config/aliases
ln -sf /home/cupcake/code/dotfiles/config/mimeapps.list ~/.config/mimeapps.list
ln -sf /home/cupcake/code/dotfiles/config/redshift.conf ~/.config/redshift.conf
ln -sf /home/cupcake/code/dotfiles/config/config ~/.config/config
ln -sf /home/cupcake/code/dotfiles/config/gtk-3.0 ~/.config/gtk-3.0
ln -sf /home/cupcake/code/dotfiles/config/polybar ~/.config/polybar
ln -sf /home/cupcake/code/dotfiles/config/termite ~/.config/termite
ln -sf /home/cupcake/code/dotfiles/config/vscode ~/.config/vscode
ln -sf /home/cupcake/code/dotfiles/zsh/dracula.zsh-theme ./oh-my-zsh/themes/dracula.zsh-theme
